name: EoT Deployment Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -l
      - run: ls -l blockchain-processor
      - run: cat blockchain-processor/package.json
      - run: npm test --prefix blockchain-processor
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Create Virtual Environment
        run: python -m venv venv
      - name: Activate Virtual Environment
        run: source venv/bin/activate
      - name: Check pip version
        run: pip --version
      - name: Install pytest
        run: pip install pytest
      - name: Check pytest version
        run: pytest --version
      - name: Check PATH
        run: echo $PATH
      - name: Run pytest
        run: ./venv/bin/pytest iot-simulator/tests/ # or where ever pytest is located.
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: kubectl apply -f k8s/