name: EoT Deployment Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -l
      - run: ls -l blockchain-processor
      - run: cat blockchain-processor/package.json
      - run: npm test --prefix blockchain-processor
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Or the version of python your project uses
      - name: Install pytest
        run: pip install pytest
      - run: pytest iot-simulator/tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: kubectl apply -f k8s/